- import_tasks: pgsql_version.yml

- name: Set PGSQL version
  set_fact:
    pgsql_version: "{{ pgsql_version_check['stdout'] | pgsql_version_string }}"
  tags:
    - always

- include_tasks: "{{ pgsqlrep_role }}.yml"
  when: pgsqlrep_role != 'skip'
