dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint -x 204,403,502,301,302
  yamllint -c molecule/default/yamllint.yml .
platforms:
  - name: pgsql-replication-test-master
    groups:
      - tower
      - database
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-centos7}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes

  - name: pgsql-replication-test-replica1
    groups:
      - database
      - database_replica
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-centos7}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes

  - name: pgsql-replication-test-replica2
    groups:
      - database
      - database_replica
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-centos7}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    group_vars:
      all:
        tower_package_name: 'ansible-tower'
        tower_package_version: '3.6.2'
        tower_package_release: '1'
        pgsqlrep_password: 'SammyDrakeSaturn'
        postgres_password: 'GnomeTutuPig'
      database:
        pgsqlrep_role: master
      database_replica:
        pgsqlrep_role: replica
scenario:
  name: default
verifier:
  name: ansible
